---
- name: Add Elastic GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Install Filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present
    update_cache: yes

- name: Deploy Filebeat config
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0644"

- name: Enable and start Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: started
    enabled: yes
    daemon_reload: yes
