[lb]
poc-lb ansible_host=207.154.220.185 private_ip=10.10.0.6

[app_servers]
poc-app1 ansible_host=139.59.211.211 private_ip=10.10.0.3
poc-app2 ansible_host=68.183.69.212 private_ip=10.10.0.8

[rabbitmq]
poc-rabbitmq ansible_host=64.226.75.184 private_ip=10.10.0.4

[consumer]
poc-consumer ansible_host=46.101.195.113 private_ip=10.10.0.5

[postgresql]
poc-postgresql ansible_host=159.89.18.117 private_ip=10.10.0.7

[elk]
poc-elk ansible_host=165.232.125.103 private_ip=10.10.0.2

[nginx:children]
lb
app_servers

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
