[lb]
poc-lb ansible_host=161.35.68.7 private_ip=10.10.0.8

[app_servers]
poc-app1 ansible_host=46.101.191.156 private_ip=10.10.0.7
poc-app2 ansible_host=164.92.176.9 private_ip=10.10.0.5

[rabbitmq]
poc-rabbitmq ansible_host=159.89.11.157 private_ip=10.10.0.2

[consumer]
poc-consumer ansible_host=46.101.174.73 private_ip=10.10.0.6

[postgresql]
poc-postgresql ansible_host=209.38.248.222 private_ip=10.10.0.3

[elk]
poc-elk ansible_host=164.92.134.219 private_ip=10.10.0.4

[nginx:children]
lb
app_servers

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
