[lb]
poc-lb ansible_host=46.101.216.198 private_ip=10.10.0.7

[app_servers]
poc-app1 ansible_host=104.248.129.85 private_ip=10.10.0.8
poc-app2 ansible_host=165.232.64.93 private_ip=10.10.0.6

[rabbitmq]
poc-rabbitmq ansible_host=46.101.135.18 private_ip=10.10.0.4

[consumer]
poc-consumer ansible_host=209.38.239.133 private_ip=10.10.0.3

[postgresql]
poc-postgresql ansible_host=161.35.77.149 private_ip=10.10.0.2

[elk]
poc-elk ansible_host=161.35.217.184 private_ip=10.10.0.5

[nginx:children]
lb
app_servers

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
